(def-table "users" (:text "Users" :write-perm "admin")
  ("userid" :pkey t)
  ("username" :type :text :poster t)
  ("password" :type :text :read-perm "admin")
  ("emailid" :type :text :read-perm "admin")
  ("roles" :type (:array :text) :internal t))

(def-table "rolepermissions" (:text "Roles" :url "roles")
  ("id" :pkey t)
  ("role" :type :text :poster t)
  ("permissions" :type (:array :text))
  ("testkey" :fkey ("users" "username" "emailid")))
